@startuml
(demo) -> (soy)
(demo) -> (appengine-maven-plugin)
(demo) -> (servlet-api)
(demo) -> (commons-io)
(demo) -> (commons-fileupload)
(demo) -> (commons-lang)
(demo) -> (libphonenumber)
(demo) -> (geocoder)
(demo) -> (carrier)
(soy) --> (jsr305)
(soy) --> (error_prone_annotations)
(soy) --> (asm)
(soy) --> (asm-commons)
(soy) --> (asm-util)
(soy) --> (asm-analysis)
(soy) --> (guava)
(soy) --> (checker-qual)
(soy) --> (protobuf-java)
(soy) --> (auto-value-annotations)
(soy) --> (guice)
(soy) --> (guava)
(soy) --> (guava-testlib)
(soy) --> (auto-value)
(soy) --> (auto-value-annotations)
(soy) --> (types)
(soy) --> (error_prone_annotations)
(soy) --> (protobuf-java)
(soy) --> (asm)
(soy) --> (asm-commons)
(soy) --> (asm-util)
(soy) --> (asm-analysis)
(soy) --> (truth)
(soy) --> (truth-java8-extension)
(soy) --> (icu4j)
(soy) --> (args4j)
(soy) --> (jsr305)
(soy) --> (gson)
(soy) --> (json)
(soy) --> (ant)
(soy) --> (junit)
(soy) --> (escapevelocity)
(soy) --> (flogger)
(soy) --> (google-extensions)
(soy) --> (flogger-system-backend)
(soy) --> (fences-maven-enforcer-rule)
(soy) --> (extra-enforcer-rules)
(soy) --> (javacc)
(appengine-maven-plugin) --> (maven-plugin-api)
(appengine-maven-plugin) --> (maven-core)
(appengine-maven-plugin) --> (maven-plugin-annotations)
(appengine-maven-plugin) --> (appengine-plugins-core)
(appengine-maven-plugin) --> (commons-io)
(appengine-maven-plugin) --> (mockito-core)
(appengine-maven-plugin) --> (junit)
(appengine-maven-plugin) --> (JUnitParams)
(appengine-maven-plugin) --> (maven-verifier)
(appengine-maven-plugin) --> (checkstyle)
(appengine-maven-plugin) --> (google-java-format)
(commons-io) --> (junit-jupiter)
(commons-io) --> (junit-pioneer)
(commons-io) --> (mockito-inline)
(commons-io) --> (jimfs)
(commons-io) --> (commons-lang3)
(commons-io) --> (jmh-core)
(commons-io) --> (jmh-generator-annprocess)
(commons-fileupload) --> (junit)
(commons-fileupload) --> (servlet-api)
(commons-fileupload) --> (portlet-api)
(commons-fileupload) --> (commons-io)
(commons-lang) --> (junit)
(geocoder) --> (libphonenumber)
(geocoder) --> (prefixmapper)
(carrier) --> (libphonenumber)
(carrier) --> (prefixmapper)
@enduml